name: Build&Push Chatbot UI GHCR
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
      - '**/renovate.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-push-ghrc:
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set release version
        run: |
          VER=$(cat package.json | grep "version" | cut -f 2 -d ":" | cut -f 1 -d "+" | cut -f 1 -d , | xargs)
          echo "APP_VERSION=$VER" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=chatbot-ui
            org.opencontainers.image.description=Next.js image for the whole Chatbot UI application
            org.opencontainers.image.vendor=Kounex
          tags: |
            type=semver,pattern={{version}},value=${{ env.APP_VERSION }}-rc${{ github.run_number }},priority=50
            type=ref,event=branch
            type=raw,value=latest
            type=sha
      - name: GHCR login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Create Release with Tag for Renovate
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_VERSION }}-rc${{ github.run_number }}
          release_name: ${{ env.APP_VERSION }}-rc${{ github.run_number }}
